# Generated by Django 4.2.5 on 2024-07-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lifetime', models.CharField(max_length=100)),
                ('achievements', models.TextField()),
                ('wikipedia_link', models.URLField()),
                ('image', models.ImageField(upload_to='leaders/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='leaders.country')),
            ],
        ),
    ]
