# Generated by Django 4.2.5 on 2024-07-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='leader',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaders.country'),
        ),
        migrations.AddField(
            model_name='leader',
            name='traits',
            field=models.ManyToManyField(blank=True, to='leaders.trait'),
        ),
    ]
